name: 🐛 Bug Report
description: Report a problem with the Hetzner Kubernetes Terraform module
labels: [bug]

body:  
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Describe the issue
        
        Steps to reproduce:
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Minimal Module Configuration
      description: Show the smallest possible config that reproduces the issue (redact secrets)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Output
      description: terraform plan/apply errors, logs, or stack traces
      render: shell

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmation
      options:
        - label: I checked existing issues, discussions, and the web for similar problems
          required: true
